#pragma once

namespace AEON
{
    namespace Key
    {
        using Symbol = uint16_t;
    
        BETTER_ENUM( Mod, Symbol,
            None                    = 0,
            Shift                   = BIT( 0 ),
            Control                 = BIT( 1 ),
            Alt                     = BIT( 2 ),
            CapsLock                = BIT( 3 ),
            NumLock                 = BIT( 4 ),
            Super                   = Shift & Control,
            Hyper                   = Shift & Alt,
            Ultra                   = Control & Alt,
            Meta                    = Shift & Control & Alt
        );

        BETTER_ENUM( Code, Symbol,
            None                    = 0,

            Zero                    = '0',
            One                     = '1',
            Two                     = '2',
            Three                   = '3',
            Four                    = '4',
            Five                    = '5',
            Six                     = '6',
            Seven                   = '7',
            Eight                   = '8',
            Nine                    = '9',

            a                       = 'a',
            b                       = 'b',
            c                       = 'c',
            d                       = 'd',
            e                       = 'e',
            f                       = 'f',
            g                       = 'g',
            h                       = 'h',
            i                       = 'i',
            j                       = 'j',
            k                       = 'k',
            l                       = 'l',
            m                       = 'm',
            n                       = 'n',
            o                       = 'o',
            p                       = 'p',
            q                       = 'q',
            r                       = 'r',
            s                       = 's',
            t                       = 't',
            u                       = 'u',
            v                       = 'v',
            w                       = 'w',
            x                       = 'x',
            y                       = 'y',
            z                       = 'z',

            A                       = 'A',
            B                       = 'B',
            C                       = 'C',
            D                       = 'D',
            E                       = 'E',
            F                       = 'F',
            G                       = 'G',
            H                       = 'H',
            I                       = 'I',
            J                       = 'J',
            K                       = 'K',
            L                       = 'L',
            M                       = 'M',
            N                       = 'N',
            O                       = 'O',
            P                       = 'P',
            Q                       = 'Q',
            R                       = 'R',
            S                       = 'S',
            T                       = 'T',
            U                       = 'U',
            V                       = 'V',
            W                       = 'W',
            X                       = 'X',
            Y                       = 'Y',
            Z                       = 'Z',

            Space                   = ' ',
            Grave                   = '`',
            Tilde                   = '~',
            ExclamationMark         = '!',
            At                      = '@',
            Hash                    = '#',
            Dollar                  = '$',
            Percent                 = '%',
            Caret                   = '^',
            Ampersand               = '&',
            Asterisk                = '*',
            LeftParenthesis         = '(',
            RightParenthesis        = ')',
            Underscore              = '_',
            Plus                    = '+',
            Minus                   = '-',
            Equals                  = '=',
            LeftBracket             = '[',
            RightBracket            = ']',
            BackSlash               = '\\',
            VerticalSlash           = '|',
            LeftCurlyBracket        = '{',
            RightCurlyBracket       = '}',
            Semicolon               = ';',
            Apostrophe              = '\'',
            Colon                   = ':',
            Quote                   = '"',
            Comma                   = ',',
            Period                  = '.',
            Slash                   = '/',
            Less                    = '<',
            Greater                 = '>',
            Question                = '?',

            F1                      = 0xFF01,
            F2                      = 0xFF02,
            F3                      = 0xFF03,
            F4                      = 0xFF04,
            F5                      = 0xFF05,
            F6                      = 0xFF06,
            F7                      = 0xFF07,
            F8                      = 0xFF08,
            F9                      = 0xFF09,
            F10                     = 0xFF0A,
            F11                     = 0xFF0B,
            F12                     = 0xFF0C,

            Backspace               = 0xFF0D,
            Tab                     = 0xFF0E,
            Enter                   = 0xFF0F,
            Escape                  = 0xFFA1,
            CapsLock                = 0xFFA2,

            PrintScreen             = 0xFFA3,
            PauseBreak              = 0xFFA4,
            ScrollLock              = 0xFFA5,

            Insert                  = 0xFFA6,
            Home                    = 0xFFA7,
            PageUp                  = 0xFFA8,
            PageDown                = 0xFFA9,
            Delete                  = 0xFFAA,
            End                     = 0xFFAB,

            Left                    = 0xFFAC,
            Up                      = 0xFFAD,
            Right                   = 0xFFAE,
            Down                    = 0xFFAF,

            NP_NumLock              = 0xFFB0,
            NP_Enter                = 0xFFB1,
            NP_Home                 = 0xFFB2,
            NP_Left                 = 0xFFB3,
            NP_Up                   = 0xFFB4,
            NP_Right                = 0xFFB5,
            NP_Down                 = 0xFFB6,
            NP_PageUp               = 0xFFB7,
            NP_PageDown             = 0xFFB8,
            NP_End                  = 0xFFB9,
            NP_Insert               = 0xFFBA,
            NP_Delete               = 0xFFBB,
            NP_Equals               = 0xFFBC,
            NP_Multiply             = 0xFFBD,
            NP_Add                  = 0xFFBE,
            NP_Subtract             = 0xFFBF,
            NP_Decimal              = 0xFFC0,
            NP_Divide               = 0xFFC1, 
            NP_Zero                 = 0xFFC2,
            NP_One                  = 0xFFC3,
            NP_Two                  = 0xFFC4,
            NP_Three                = 0xFFC5,
            NP_Four                 = 0xFFC6,
            NP_Five                 = 0xFFC7,
            NP_Six                  = 0xFFC8,
            NP_Seven                = 0xFFC9,
            NP_Eight                = 0xFFCA,
            NP_Nine                 = 0xFFCB,

            Shift_L                 = 0xFFCC,
            Shift_R                 = 0xFFCD,
            Control_L               = 0xFFCE,
            Control_R               = 0xFFCF,
            Alt_L                   = 0xFFD0,
            Alt_R                   = 0xFFD1,

            Menu_L                  = 0xFFD2,
            Menu_R                  = 0xFFD3
        );

        /* Names are from en_US keyboard layout */
        BETTER_ENUM( ScanCode, Symbol,
            None                    = 0,

            KB_A                    = 4,
            KB_B                    = 5,
            KB_C                    = 6,
            KB_D                    = 7,
            KB_E                    = 8,
            KB_F                    = 9,
            KB_G                    = 10,
            KB_H                    = 11,
            KB_I                    = 12,
            KB_J                    = 13,
            KB_K                    = 14,
            KB_L                    = 15,
            KB_M                    = 16,
            KB_N                    = 17,
            KB_O                    = 18,
            KB_P                    = 19,
            KB_Q                    = 20,
            KB_R                    = 21,
            KB_S                    = 22,
            KB_T                    = 23,
            KB_U                    = 24,
            KB_V                    = 25,
            KB_W                    = 26,
            KB_X                    = 27,
            KB_Y                    = 28,
            KB_Z                    = 29,
            KB_1                    = 30,
            KB_2                    = 31,
            KB_3                    = 32,
            KB_4                    = 33,
            KB_5                    = 34,
            KB_6                    = 35,
            KB_7                    = 36,
            KB_8                    = 37,
            KB_9                    = 38,
            KB_0                    = 39,

            KB_Escape               = 41,
            KB_Backspace            = 42,
            KB_Tab                  = 43,
            KB_Space                = 44,
            KB_Minus                = 45,
            KB_Equals               = 46,
            KB_LeftBracket          = 47,
            KB_RightBracket         = 48,
            KB_Backslash            = 49,
            KB_Semicolon            = 51,
            KB_Quote                = 52,
            KB_Grave                = 53,
            KB_Comma                = 54,
            KB_Period               = 55,
            KB_Slash                = 56,
            KB_CapsLock             = 57,

            KB_F1                   = 58,
            KB_F2                   = 59,
            KB_F3                   = 60,
            KB_F4                   = 61,
            KB_F5                   = 62,
            KB_F6                   = 63,
            KB_F7                   = 64,
            KB_F8                   = 65,
            KB_F9                   = 66,
            KB_F10                  = 67,
            KB_F11                  = 68,
            KB_F12                  = 69,

            KB_PrintScreen          = 70,
            KB_ScrollLock           = 71,
            KB_Pause                = 72,
            KB_Insert               = 73,
            KB_Home                 = 74,
            KB_PageUp               = 75,
            KB_Delete               = 76,
            KB_End                  = 77,
            KB_PageDown             = 78,
            KB_Right                = 79,
            KB_Left                 = 80,
            KB_Down                 = 81,
            KB_Up                   = 82,

            NP_NumLock              = 83,
            NP_Divide               = 84,
            NP_Multiply             = 85,
            NP_Subtract             = 86,
            NP_Add                  = 87,
            NP_Enter                = 88,
            NP_1                    = 89,
            NP_2                    = 90,
            NP_3                    = 91,
            NP_4                    = 92,
            NP_5                    = 93,
            NP_6                    = 94,
            NP_7                    = 95,
            NP_8                    = 96,
            NP_9                    = 97,
            NP_0                    = 98,
            NP_Decimal              = 99,

            KB_NonUSBackslash       = 100,

            NP_Equals               = 103,

            KB_F13                  = 104,
            KB_F14                  = 105,
            KB_F15                  = 106,
            KB_F16                  = 107,
            KB_F17                  = 108,
            KB_F18                  = 109,
            KB_F19                  = 110,
            KB_F20                  = 111,
            KB_F21                  = 112,
            KB_F22                  = 113,
            KB_F23                  = 114,
            KB_F24                  = 115,

            KB_Help                 = 117,
            KB_Menu                 = 118,
            KB_Mute                 = 127,
            KB_SysReq               = 154,
            KB_Return               = 158,

            NP_Clear                = 216,
            NP_Point                = 220,

            KB_LeftControl          = 224,
            KB_LeftShift            = 225,
            KB_LeftAlt              = 226,
            KB_LeftMenu             = 227,
            KB_RightControl         = 228,
            KB_RightShift           = 229,
            KB_RightAlt             = 230,
            KB_RightMenu            = 231
        );
    }
}